project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "Data Visualization"
        href: data_visualization.html
      - text: "Reflection"
        href: reflection.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



